sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
php:
- 5.6
- 7.1
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=inc@2inc.org
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=inc@2inc.org
  - WP_VERSION=latest WP_MULTISITE=0
cache:
  directories:
  - node_modules
  - vendor
  - "$HOME/.composer/cache"
install:
- nvm install 6
- npm install -g yarn
- yarn install
- npm rebuild node-sass
- composer install
script:
- composer test
after_success:
- pwd
- ls -al
before_deploy:
- rsync -a . release
- cd release
- rm -rf vendor
- composer install --no-dev
- yarn run gulp zip
- ls -la snow-monkey-design-skin-spring.zip
- export RELEASE_FILE=$(ls snow-monkey-design-skin-spring.zip)
deploy:
  provider: releases
  api_key:
    secure: eUEho564r1IIM+oUr7+pXlEFK4h5U2TNvtcJE2pbCeeenP7ZAkVbBr6JXrZdikP70+8FyH5Zx58AzssC5nR15n1zDCVUHMleE6J1AZU2Hqux8IqH+yJwfndcCKK2GnsOA0zcl0ersr45fm753J5vel/oO2s6VkyBhYo/dEnBOoxm5W/hkfbUN1LlNsEYfPqb4BKXOIBQlYUJbTAw17vymAWpm66HZwH9BtRYd3UFG/ZXcyfO4QXL9A9q1YkmH2yF+5t0uaX1cW+fgmQAWrSjqVfou2lBC58IVv1S8NwNh5x+bAoypZaL2e+9lffl1nVuun9SBfcIIZsFrgl2ZBtkBtx/Hr8OJAi/jicbSIfdpLcwqMsJLHfE8aZynoPw4cnXekrn0i3mHIJ7/ACJE239gvS3alDduoUufJuz+RhPbhVRnJ0z10NZLWT1BmlDkrDB7bUWBFvb6aFtXvIFtavkyJQeeVOjKrxRukXLfX0Jcgg8M+8hU1Ac/RhiCrs8zqnIEuVFwiLVuiKvzl1MQTCe56YznVz3ypXT7Jo8uNBjAOFqB7mW7xQhES1UVMzT/pB5tYqSbfHgBFk21WXk+f3QRVZfw38KKjTbsLjF6dXX1ZViskyVtQDcqybgIES7+zXaYGiVLTQKklEzaotfWCxaN1DkouqdrZ+uw+ZiwrfwQwM=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: inc2734/snow-monkey-design-skin-spring
